defaultPulsarImageTag: 3.0.0
## deployed withh emptyDir
volumes:
  persistence: false

# disabled AntiAffinity
affinity:
  anti_affinity: false

# disable auto recovery
components:
  autorecovery: false
  pulsar_manager: false
  monitoring: false

zookeeper:
  replicaCount: 3

bookkeeper:
  replicaCount: 3

broker:
  replicaCount: 3
  configData:
    autoSkipNonRecoverableData: "true"
    managedLedgerDefaultEnsembleSize: "2"
    managedLedgerDefaultWriteQuorum: "2"
    managedLedgerDefaultAckQuorum: "2"

proxy:
  replicaCount: 1
  ports:
    # Pulsar on MicroK8S cannot open port 80
    http: "8080"

toolset:
  configData:
    # Pulsar on MicroK8S cannot open port 80
    webServiceUrl: "http://pulsar-proxy:8080/"
